title: Julz Labs
baseURL: https://julzlabs.netlify.app
markup:
  goldmark:
    renderer:
      unsafe: true
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
author:
  name: Julz Labs
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.
languageCode: en-us
watch: true
